### ISSUE TITLE
Checking online twitch streams no longer works due to twitch API changes

### ISSUE THREAD

**Issue by diuXd9gfdwco2P** [gapato/livestreamer-curses#22]
All the streams are marked offline with a '!' status, even though some of them are clearly online on the twitch site.

Watching streams doesn't normally work either , but this one is fixable by adding your twitch-oauth-token in your rcfile (livestreamer command)  : https://github.com/chrippa/livestreamer/issues/1456#issuecomment-247192307

**Comment by ThatLurker** [comment]
Yeah this project seems dead, you better search for an alternative here:
https://github.com/chrippa/livestreamer/wiki/Alternative-interfaces

**Comment by marteaurouge** [comment]
strimgo looks great

**Comment by diuXd9gfdwco2P** [comment]
Thanks for the suggestions. I'm trying strimgo right now. It isn't as good as livestreamer-curses was(it can't handle non-twitch streams) , but it does the job right.

**Comment by Hund** [comment]
I modified a version of livestreamer-curses to use streamlink instead of livestreamer. It works just fine, but one thing I don't like with the new API is that it shows the person as online even if they're just hosting another channel.

I'm in no way a coder so I have no idea how to fix that. But if you want to have a look at my working version you can find it here: https://github.com/Hund/livestreamer-curses
